### ISSUE TITLE
[Docs] What is the version of mmcv？

### ISSUE THREAD

**Issue by fzu021800901** [zcablii/LSKNet#10]
### Branch

master branch  https://mmrotate.readthedocs.io/en/latest/

### 📚 The doc issue

  "Default process group has not been initialized, "
RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.
root@csip-108:/mnt/csip-107/mmrotate/tools# 

lsknet.py
Can not from mmcv.cnn.utils.weight_init import (constant_init, normal_init,
                                        trunc_normal_init)

Mine : mmcv-2.0.0  mmrotate-0.3.4

**Comment by zcablii** [comment]
Here is my environment (by ```conda env export```):

name: mmrotate
channels:
  - pytorch
  - nvidia
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - brotlipy=0.7.0=py38h27cfd23_1003
  - ca-certificates=2023.5.7=hbcca054_0
  - certifi=2023.5.7=pyhd8ed1ab_0
  - cffi=1.14.3=py38h261ae71_2
  - chardet=3.0.4=py38h06a4308_1003
  - conda-pack=0.7.0=pyh6c4a22f_0
  - conda-package-handling=1.7.2=py38h03888b9_0
  - cryptography=3.2.1=py38h3c74f83_1
  - cudatoolkit=11.0.221=h6bb024c_0
  - freetype=2.10.4=h5ab3b9f_0
  - idna=2.10=py_0
  - intel-openmp=2021.2.0=h06a4308_610
  - jpeg=9b=h024ee3a_2
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - libuv=1.40.0=h7b6447c_0
  - lz4-c=1.9.3=h2531618_0
  - mkl=2021.2.0=h06a4308_296
  - mkl-service=2.3.0=py38h27cfd23_1
  - mkl_fft=1.3.0=py38h42c9631_2
  - mkl_random=1.2.1=py38ha9443f7_2
  - ncurses=6.2=he6710b0_1
  - ninja=1.10.2=hff7bd54_1
  - numpy-base=1.20.1=py38h7d8b39e_0
  - olefile=0.46=py_0
  - openssl=1.1.1t=h7f8727e_0
  - pillow=8.2.0=py38he98fc37_0
  - pip=20.2.4=py38h06a4308_0
  - pycosat=0.6.3=py38h7b6447c_1
  - pycparser=2.20=py_2
  - pyopenssl=19.1.0=pyhd3eb1b0_1
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.5=h7579374_1
  - python_abi=3.8=2_cp38
  - pytorch=1.7.1=py3.8_cuda11.0.221_cudnn8.0.5_0
  - readline=8.0=h7b6447c_0
  - requests=2.24.0=py_0
  - ruamel_yaml=0.15.87=py38h7b6447c_1
  - setuptools=50.3.1=py38h06a4308_1
  - six=1.15.0=py38h06a4308_0
  - sqlite=3.33.0=h62c20be_0
  - tk=8.6.10=hbc83047_0
  - toolz=0.12.0=pyhd8ed1ab_0
  - tqdm=4.51.0=pyhd3eb1b0_0
  - typing_extensions=3.7.4.3=pyha847dfd_0
  - urllib3=1.25.11=py_0
  - wheel=0.35.1=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.9=haebb681_0
  - pip:
      - addict==2.4.0
      - asttokens==2.1.0
      - backcall==0.2.0
      - click==8.1.3
      - colorama==0.4.6
      - commonmark==0.9.1
      - contourpy==1.0.6
      - cycler==0.11.0
      - cython==0.29.32
      - debugpy==1.6.3
      - decorator==5.1.1
      - e2cnn==0.2.2
      - entrypoints==0.4
      - executing==1.2.0
      - fonttools==4.38.0
      - importlib-metadata==5.0.0
      - ipykernel==6.17.1
      - ipython==8.6.0
      - jedi==0.18.1
      - jupyter-client==7.4.7
      - jupyter-core==5.0.0
      - kiwisolver==1.4.4
      - markdown==3.4.1
      - matplotlib==3.6.2
      - matplotlib-inline==0.1.6
      - mmcv-full==1.7.0
      - mmdet==2.25.3
      - model-index==0.1.11
      - mpmath==1.2.1
      - nest-asyncio==1.5.6
      - numpy==1.23.4
      - opencv-python==4.6.0.66
      - opencv-python-headless==4.6.0.66
      - openmim==0.3.3
      - ordered-set==4.1.0
      - packaging==21.3
      - pandas==1.5.1
      - parso==0.8.3
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - platformdirs==2.5.4
      - prompt-toolkit==3.0.32
      - psutil==5.9.4
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pycocotools==2.0.6
      - pygments==2.13.0
      - pyparsing==3.0.9
      - python-dateutil==2.8.2
      - pytz==2022.6
      - pyyaml==6.0
      - pyzmq==24.0.1
      - rich==12.6.0
      - scipy==1.9.3
      - shapely==1.8.5.post1
      - stack-data==0.6.1
      - sympy==1.11.1
      - tabulate==0.9.0
      - terminaltables==3.1.10
      - timm==0.3.2
      - torch==1.7.1+cu110
      - torchaudio==0.7.2
      - torchvision==0.8.2+cu110
      - tornado==6.2
      - traitlets==5.5.0
      - typing-extensions==4.4.0
      - wcwidth==0.2.5
      - yapf==0.32.0
      - zipp==3.10.0
prefix: /home/u9920220020/lyx/data/mmrotate

**Comment by mrbjkk** [comment]
Same error. Did you find any solution? Thanks in advance.

> ### Branch
> master branch https://mmrotate.readthedocs.io/en/latest/
> 
> ### 📚 The doc issue
> "Default process group has not been initialized, " RuntimeError: Default process group has not been initialized, please make sure to call init_process_group. root@csip-108:/mnt/csip-107/mmrotate/tools#
> 
> lsknet.py Can not from mmcv.cnn.utils.weight_init import (constant_init, normal_init, trunc_normal_init)
> 
> Mine : mmcv-2.0.0 mmrotate-0.3.4
> 
> ### Suggest a potential alternative/fix
> _No response_
