### ISSUE TITLE
[Feature] 将lskblock加入yolov5

### ISSUE THREAD

**Issue by dashanlidewa** [zcablii/LSKNet#13]
### What's the feature?

我想将LSKblock加入yolov5-v7，使用的LSKblock代码以及模型配置文件如下
![image](https://github.com/zcablii/Large-Selective-Kernel-Network/assets/50894654/39295cf8-0d1c-49c3-9201-2d7c2cd30db5)
![image](https://github.com/zcablii/Large-Selective-Kernel-Network/assets/50894654/0540f1e5-6db7-410e-9313-697f491f800f)

然而出现了梯度爆炸，当我使用SKblock或者使用原始yolo模型的时候模型可以正常训练，SKblock如下所示
![image](https://github.com/zcablii/Large-Selective-Kernel-Network/assets/50894654/fe64cc35-7673-45f4-88df-6c117f6d1c8f)
LSKblock的dim参数传递的应该是正确的，如下图
![image](https://github.com/zcablii/Large-Selective-Kernel-Network/assets/50894654/379cabd1-68e1-451a-9e51-9060b54e71f1)
我不知道哪里出了问题，是和激活函数有关吗

**Comment by zcablii** [comment]
请问`LSKblock`有没有初始化权重？或者降低lr试试？或是适当调整`LSKblock`，比如：将LSKblock的两个decomposed kernel调小一些，或插入一些normlization层。

**Comment by dashanlidewa** [comment]
> 请问`LSKblock`有没有初始化权重？或者降低lr试试？或是适当调整`LSKblock`，比如：将LSKblock的两个decomposed kernel调小一些，或插入一些normlization层。

在输出后面加了个bn后果然好了，感谢
![image](https://github.com/zcablii/Large-Selective-Kernel-Network/assets/50894654/c9391a86-6bd7-4c61-a473-23f0c6dbedfc)

**Comment by liiicon** [comment]
> > 请问`LSKblock`有没有初始化权重？或者降低lr试试？或是适当调整`LSKblock`，比如：将LSKblock的两个decomposed kernel调小一些，或插入一些normlization层。
> 
> 在输出后面加了个bn后果然好了，感谢 ![image](https://user-images.githubusercontent.com/50894654/248537792-c9391a86-6bd7-4c61-a473-23f0c6dbedfc.png)

我在v7tiny backbone的elan后加上LSK,且加上bn层和act还是无法收敛

**Comment by liiicon** [comment]
![image](https://github.com/zcablii/LSKNet/assets/69030185/b82a0a66-72be-455a-84a5-c2adbbdf8f09)

**Comment by dashanlidewa** [comment]
> ![image](https://user-images.githubusercontent.com/69030185/254160743-b82a0a66-72be-455a-84a5-c2adbbdf8f09.png)

我在注意力输入端，就是第一层卷积前加bn也能收敛，你可以试试，不过感觉对你应该没用，我自己数据集上的效果lsk效果掉了5个点（加在backbone和head上都会掉），加的越多掉的越多，v7倒是不太清楚

**Comment by nyj-ocean** [comment]
@dashanlidewa 
您好，想请教一下，在YOLOv5中，将`LSKblock`模块加入`common.py`文件后，`yolo.py`文件中如何添加与修改呢？https://github.com/zcablii/LSKNet/issues/13#issue-1766915787

另外，加入了归一化`return self.norml( x * attn)`后，为何会报错呢？错误如下：
```
  File "F:\User\nyj\yolov5-master\models\lsk.py", line 78, in forward
    return self.norml(x * attn)
  File "F:\ProgramData\Anaconda3\envs\yolov5\lib\site-packages\torch\nn\modules\module.py", line 947, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'LSKblock' object has no attribute 'norml'
```
https://github.com/zcablii/LSKNet/issues/13#issuecomment-1605913733

**Comment by dashanlidewa** [comment]
> @dashanlidewa 您好，想请教一下，在YOLOv5中，将`LSKblock`模块加入`common.py`文件后，`yolo.py`文件中如何添加与修改呢？[#13 (comment)](https://github.com/zcablii/LSKNet/issues/13#issue-1766915787)
> 
> 另外，加入了归一化`return self.norml( x * attn)`后，为何会报错呢？错误如下：
> 
> ```
>   File "F:\User\nyj\yolov5-master\models\lsk.py", line 78, in forward
>     return self.norml(x * attn)
>   File "F:\ProgramData\Anaconda3\envs\yolov5\lib\site-packages\torch\nn\modules\module.py", line 947, in __getattr__
>     raise AttributeError("'{}' object has no attribute '{}'".format(
> AttributeError: 'LSKblock' object has no attribute 'norml'
> ```
> 
> [#13 (comment)](https://github.com/zcablii/LSKNet/issues/13#issuecomment-1605913733)

![image](https://github.com/zcablii/LSKNet/assets/50894654/7d56a505-e98c-4f1e-9cb2-6bd8938a38f7)
你也可以重新写个elif，然后norm1需要你在构造函数里面定义，如下图
![image](https://github.com/zcablii/LSKNet/assets/50894654/1217b979-63f3-4f31-9ca0-a41066912533)

**Comment by yang19950411** [comment]
> 
你好，想请问下该如何初始化权重，我在v7上应用时报错说缺少dim参数
![image](https://github.com/zcablii/LSKNet/assets/88123195/4b011214-1850-49c6-9800-9c9d8b9a4ad6)

**Comment by yang19950411** [comment]
> 请问`LSKblock`有没有初始化权重？或者降低lr试试？或是适当调整`LSKblock`，比如：将LSKblock的两个decomposed kernel调小一些，或插入一些normlization层。

你好，想请问下该如何初始化权重，我在v7上应用时报错说缺少dim参数
![image](https://github.com/zcablii/LSKNet/assets/88123195/622d355b-9d20-4ae6-97f8-4d991e26de6e)

**Comment by yang19950411** [comment]
> 然后norm1需要你在构造函数里面定义，如下图

您好，想请教一下，按照您给出的步骤在yolov5中做出了相应的修改，还是出现了报错，以下是相应修改和报错信息，您能帮忙看下问题出在哪吗？
![image](https://github.com/zcablii/LSKNet/assets/88123195/652baf0b-8aaa-4354-b8f9-353f133cd3e4)
![image](https://github.com/zcablii/LSKNet/assets/88123195/694cc167-c8ef-4488-91dd-8720bd6bac1f)
![image](https://github.com/zcablii/LSKNet/assets/88123195/b0ac8228-9d39-447a-95c2-a5445d040b52)
![image](https://github.com/zcablii/LSKNet/assets/88123195/c120b6aa-6dab-454e-bac5-28f7e49e7ba7)
![image](https://github.com/zcablii/LSKNet/assets/88123195/7c882544-6ae5-4dc0-b753-1ab2e4a65df9)

![image](https://github.com/zcablii/LSKNet/assets/88123195/430e153f-2f79-4798-af3c-c03f849ca4ab)

**Comment by dashanlidewa** [comment]
LSKblock放错位置了，别放在那个Conv开头的集合里，而且配置文件里
![image](https://github.com/zcablii/LSKNet/assets/50894654/bb697442-7751-41b3-ad33-c758b950e0b3)
args是空的，所以索引就出错了，直接args=[ch[f]]就可以了

**Comment by dashanlidewa** [comment]
> > 然后norm1需要你在构造函数里面定义，如下图
> 
> 您好，想请教一下，按照您给出的步骤在yolov5中做出了相应的修改，还是出现了报错，以下是相应修改和报错信息，您能帮忙看下问题出在哪吗？ ![image](https://user-images.githubusercontent.com/88123195/258760997-652baf0b-8aaa-4354-b8f9-353f133cd3e4.png) ![image](https://user-images.githubusercontent.com/88123195/258761019-694cc167-c8ef-4488-91dd-8720bd6bac1f.png) ![image](https://user-images.githubusercontent.com/88123195/258761144-b0ac8228-9d39-447a-95c2-a5445d040b52.png) ![image](https://user-images.githubusercontent.com/88123195/258761088-c120b6aa-6dab-454e-bac5-28f7e49e7ba7.png) ![image](https://user-images.githubusercontent.com/88123195/258761223-7c882544-6ae5-4dc0-b753-1ab2e4a65df9.png)
> 
> ![image](https://user-images.githubusercontent.com/88123195/258761665-430e153f-2f79-4798-af3c-c03f849ca4ab.png)

![image](https://github.com/zcablii/LSKNet/assets/50894654/196b3063-e9b8-455c-8c93-0847fd255fa3)

**Comment by dashanlidewa** [comment]
> > 然后norm1需要你在构造函数里面定义，如下图
> 
> 您好，想请教一下，按照您给出的步骤在yolov5中做出了相应的修改，还是出现了报错，以下是相应修改和报错信息，您能帮忙看下问题出在哪吗？ ![image](https://user-images.githubusercontent.com/88123195/258760997-652baf0b-8aaa-4354-b8f9-353f133cd3e4.png) ![image](https://user-images.githubusercontent.com/88123195/258761019-694cc167-c8ef-4488-91dd-8720bd6bac1f.png) ![image](https://user-images.githubusercontent.com/88123195/258761144-b0ac8228-9d39-447a-95c2-a5445d040b52.png) ![image](https://user-images.githubusercontent.com/88123195/258761088-c120b6aa-6dab-454e-bac5-28f7e49e7ba7.png) ![image](https://user-images.githubusercontent.com/88123195/258761223-7c882544-6ae5-4dc0-b753-1ab2e4a65df9.png)
> 
> ![image](https://user-images.githubusercontent.com/88123195/258761665-430e153f-2f79-4798-af3c-c03f849ca4ab.png)

LSKblock别放在Conv开头的集合里，而且配置文件
![image](https://github.com/zcablii/LSKNet/assets/50894654/f6bd8c38-f875-47b6-8d12-fca8a1469d23)
里面args是空的，所以索引报错，让args = [c2]就行了

**Comment by yang19950411** [comment]
> > > 然后norm1需要你在构造函数里面定义，如下图
> > 
> > 
> > 您好，想请教一下，按照您给出的步骤在yolov5中做出了相应的修改，还是出现了报错，以下是相应修改和报错信息，您能帮忙看下问题出在哪吗？ ![image](https://user-images.githubusercontent.com/88123195/258760997-652baf0b-8aaa-4354-b8f9-353f133cd3e4.png) ![image](https://user-images.githubusercontent.com/88123195/258761019-694cc167-c8ef-4488-91dd-8720bd6bac1f.png) ![image](https://user-images.githubusercontent.com/88123195/258761144-b0ac8228-9d39-447a-95c2-a5445d040b52.png) ![image](https://user-images.githubusercontent.com/88123195/258761088-c120b6aa-6dab-454e-bac5-28f7e49e7ba7.png) ![image](https://user-images.githubusercontent.com/88123195/258761223-7c882544-6ae5-4dc0-b753-1ab2e4a65df9.png)
> > ![image](https://user-images.githubusercontent.com/88123195/258761665-430e153f-2f79-4798-af3c-c03f849ca4ab.png)
> 
> LSKblock别放在Conv开头的集合里，而且配置文件 ![image](https://user-images.githubusercontent.com/50894654/258765775-f6bd8c38-f875-47b6-8d12-fca8a1469d23.png) 里面args是空的，所以索引报错，让args = [c2]就行了

好的，问题解决了，非常感谢。

**Comment by zcablii** [comment]
![image](https://github.com/zcablii/LSKNet/assets/32335301/2b41588b-2172-4447-babf-270af76b8a21)
LSKBlock() in code actually corresponds to LSK module in the paper (Sorry for the confusion). The BN is added to the LSK block (corresponding to the Block() in the code). We have never tried to add BN in LSK module.

**Comment by NWPU-Li** [comment]
> ![image](https://user-images.githubusercontent.com/32335301/259353762-2b41588b-2172-4447-babf-270af76b8a21.png) LSKBlock() in code actually corresponds to LSK module in the paper (Sorry for the confusion). The BN is added to the LSK block (corresponding to the Block() in the code). We have never tried to add BN in LSK module.

ok，thank you
