### ISSUE TITLE
lsknet

### ISSUE THREAD

**Issue by zhu011** [zcablii/LSKNet#21]
### Branch

master branch  https://mmrotate.readthedocs.io/en/latest/

### 📚 The doc issue

作者大佬，后续有没有可能出更深层的预训练权重。。

**Comment by zcablii** [comment]
暂时手上没有资源跑更深层lsknet的预训练了。不过可以自行训练，预训练代码可参考 [https://github.com/huggingface/pytorch-image-models](url)

**Comment by NWPU-Li** [comment]
> 暂时手上没有资源跑更深层lsknet的预训练了。不过可以自行训练，预训练代码可参考 [https://github.com/huggingface/pytorch-image-models](url)
您好，我保存的“LSKNet-S”参数怎么比文章中给出的差这么多呢。。。
![image](https://github.com/zcablii/LSKNet/assets/56581796/0cd4ca29-aacc-4094-82b1-e8f96c716be5)

**Comment by zcablii** [comment]
您可以用这个工具来计算模型参数量 [https://github.com/zcablii/LSKNet/blob/main/tools/analysis_tools/get_flops.py](url)
