### ISSUE TITLE
[Feature] 请问LSKNet是否支持连接ReFPN？

### ISSUE THREAD

**Issue by 330205812** [zcablii/LSKNet#23]
### What's the feature?

尊敬的LSKNet作者及社区维护人你们好！

我想咨询一下LSKNet是否支持链接ReFPN，如果支持的话，下面是我的config以及报错信息，希望可以帮忙看下是哪里出了问题，谢谢！

![image](https://github.com/zcablii/LSKNet/assets/62977356/9afbb6ec-ec81-472d-ab0e-83244d7dbed4)

![IPH}3`6FHQ}{J6BQP}KLR$0](https://github.com/zcablii/LSKNet/assets/62977356/c1306c0b-6a9d-41ff-92b5-c40ad49766a9)

**Comment by zcablii** [comment]
seems not to support ReFPN
