### ISSUE TITLE
[Docs] 

### ISSUE THREAD

**Issue by SabraHashemi** [zcablii/LSKNet#24]
### Branch

master branch  https://mmrotate.readthedocs.io/en/latest/

### 📚 The doc issue

I've searched about the FPS of this code in your docs to make sure that i'm on the right way, but I've got nothing
can you add more info about the fps?

### Suggest a potential alternative/fix

addinfo about system specs and value of fps on it

**Comment by zcablii** [comment]
try `python -m torch.distributed.launch --nproc_per_node=1 --master_port=29500 tools/analysis_tools/benchmark.py \
       configs/rotated_faster_rcnn/rotated_faster_rcnn_r50_fpn_1x_dota_le90.py \
       checkpoints/rotated_faster_rcnn_r50_fpn_1x_dota_le90-0393aa5c.pth \
       --launcher pytorch`
as mentioned in [https://github.com/zcablii/LSKNet/blob/main/docs/en/useful_tools.md#benchmark](url)
