### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by 2276924877** [zcablii/LSKNet#26]
### What's the feature?

Hello author, Figure 5 in this paper shows that LSKnet's feature map visualization effect is better than resnet-50. Could you please provide your feature map visualization code?
![image](https://github.com/zcablii/LSKNet/assets/71757421/f5147828-4cc1-4857-9b1f-4fd6c1ef8f4c)

**Comment by zcablii** [comment]
I implemented it based on this Repo: https://github.com/jacobgil/pytorch-grad-cam
