### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by YangGuobao** [zcablii/LSKNet#30]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmrotate/issues) and [Discussions](https://github.com/open-mmlab/mmrotate/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmrotate.readthedocs.io/en/1.x/notes/4_faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmrotate) or [latest version (1.x)](https://github.com/open-mmlab/mmrotate/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmrotate

### Environment

# Name                    Version                   Build  Channel
addict                    2.4.0                    pypi_0    pypi
aliyun-python-sdk-core    2.14.0                   pypi_0    pypi
aliyun-python-sdk-kms     2.16.2                   pypi_0    pypi
blas                      1.0                         mkl
brotlipy                  0.7.0           py38h2bbff1b_1003
ca-certificates           2023.08.22           haa95532_0
certifi                   2023.7.22        py38haa95532_0
cffi                      1.16.0                   pypi_0    pypi
chardet                   5.2.0                    pypi_0    pypi
charset-normalizer        3.3.0                    pypi_0    pypi
click                     8.1.7                    pypi_0    pypi
colorama                  0.4.6                    pypi_0    pypi
contourpy                 1.1.1                    pypi_0    pypi
crcmod                    1.7                      pypi_0    pypi
cryptography              41.0.4                   pypi_0    pypi
cudatoolkit               11.8.0               hd77b12b_0
cycler                    0.12.1                   pypi_0    pypi
filelock                  3.9.0            py38haa95532_0
fonttools                 4.43.1                   pypi_0    pypi
freetype                  2.12.1               ha860e81_0
fsspec                    2023.9.2                 pypi_0    pypi
giflib                    5.2.1                h8cc25b3_3
huggingface-hub           0.17.3                   pypi_0    pypi
idna                      3.4              py38haa95532_0
importlib-metadata        6.8.0                    pypi_0    pypi
importlib-resources       6.1.0                    pypi_0    pypi
intel-openmp              2023.1.0         h59b6b97_46319
jinja2                    3.1.2            py38haa95532_0
jmespath                  0.10.0                   pypi_0    pypi
jpeg                      9e                   h2bbff1b_1
kiwisolver                1.4.5                    pypi_0    pypi
lerc                      3.0                  hd77b12b_0
libdeflate                1.17                 h2bbff1b_1
libffi                    3.4.4                hd77b12b_0
libjpeg-turbo             2.0.0                h196d8e1_0
libpng                    1.6.39               h8cc25b3_0
libtiff                   4.5.1                hd77b12b_0
libuv                     1.44.2               h2bbff1b_0
libwebp                   1.3.2                hbc33d0d_0
libwebp-base              1.3.2                h2bbff1b_0
lz4-c                     1.9.4                h2bbff1b_0
markdown                  3.5                      pypi_0    pypi
markdown-it-py            3.0.0                    pypi_0    pypi
markupsafe                2.1.1            py38h2bbff1b_0
matplotlib                3.7.3                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
mkl                       2023.1.0         h6b88ed4_46357
mkl-service               2.4.0            py38h2bbff1b_1
mkl_fft                   1.3.8            py38h2bbff1b_0
mkl_random                1.2.4            py38h59b6b97_0
mmcv-full                 1.7.1                    pypi_0    pypi
mmdet                     2.28.1                   pypi_0    pypi
mmrotate                  0.3.4                    pypi_0    pypi
model-index               0.1.11                   pypi_0    pypi
mpmath                    1.3.0            py38haa95532_0
networkx                  3.1              py38haa95532_0
numpy                     1.24.4                   pypi_0    pypi
numpy-base                1.24.3           py38h8a87ada_1
opencv-python             4.8.1.78                 pypi_0    pypi
opendatalab               0.0.10                   pypi_0    pypi
openjpeg                  2.4.0                h4fc8c34_0
openmim                   0.3.9                    pypi_0    pypi
openssl                   3.0.11               h2bbff1b_2
openxlab                  0.0.26                   pypi_0    pypi
ordered-set               4.1.0                    pypi_0    pypi
oss2                      2.17.0                   pypi_0    pypi
packaging                 23.2                     pypi_0    pypi
pandas                    2.0.3                    pypi_0    pypi
pillow                    10.0.1           py38h045eedc_0
pip                       23.2.1           py38haa95532_0
platformdirs              3.11.0                   pypi_0    pypi
pycocotools               2.0.7                    pypi_0    pypi
pycparser                 2.21               pyhd3eb1b0_0
pycryptodome              3.19.0                   pypi_0    pypi
pygments                  2.16.1                   pypi_0    pypi
pyopenssl                 23.2.0           py38haa95532_0
pyparsing                 3.1.1                    pypi_0    pypi
pysocks                   1.7.1            py38haa95532_0
python                    3.8.18               h1aa4202_0
python-dateutil           2.8.2                    pypi_0    pypi
pytorch                   2.1.0               py3.8_cpu_0    pytorch
pytorch-mutex             1.0                         cpu    pytorch
pytz                      2023.3.post1             pypi_0    pypi
pywin32                   306                      pypi_0    pypi
pyyaml                    6.0.1                    pypi_0    pypi
regex                     2023.10.3                pypi_0    pypi
requests                  2.28.2                   pypi_0    pypi
rich                      13.4.2                   pypi_0    pypi
safetensors               0.4.0                    pypi_0    pypi
scipy                     1.10.1                   pypi_0    pypi
setuptools                60.2.0                   pypi_0    pypi
shapely                   2.0.1                    pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
sqlite                    3.41.2               h2bbff1b_0
sympy                     1.11.1           py38haa95532_0
tabulate                  0.9.0                    pypi_0    pypi
tbb                       2021.8.0             h59b6b97_0
terminaltables            3.1.10                   pypi_0    pypi
timm                      0.9.7                    pypi_0    pypi
tk                        8.6.12               h2bbff1b_0
tomli                     2.0.1                    pypi_0    pypi
torchvision               0.16.0                 py38_cpu    pytorch
tqdm                      4.65.2                   pypi_0    pypi
typing-extensions         4.8.0                    pypi_0    pypi
typing_extensions         4.7.1            py38haa95532_0
tzdata                    2023.3                   pypi_0    pypi
urllib3                   1.26.17                  pypi_0    pypi
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wheel                     0.41.2           py38haa95532_0
win_inet_pton             1.1.0            py38haa95532_0
xz                        5.4.2                h8cc25b3_0
yaml                      0.2.5                he774522_0
yapf                      0.40.2                   pypi_0    pypi
zipp                      3.17.0                   pypi_0    pypi
zlib                      1.2.13               h8cc25b3_0
zstd                      1.5.5                hd43e919_0

### Reproduces the problem - code sample

from mmdet.apis import init_detector, inference_detector
import mmrotate

config_file = 'oriented_rcnn_r50_fpn_1x_dota_le90.py'
checkpoint_file = 'oriented_rcnn_r50_fpn_1x_dota_le90-6d2b2ce0.pth'
model = init_detector(config_file, checkpoint_file, device='cuda:0')
inference_detector(model, 'demo/demo.jpg')

### Reproduces the problem - command or script

python test.py

### Reproduces the problem - error message

No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1'
F:\Anaconda\Anaconda\envs\openmmlab\lib\site-packages\mmcv\__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-
full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    model = init_detector(config_file, checkpoint_file, device='cuda:0')
  File "F:\Anaconda\Anaconda\envs\openmmlab\lib\site-packages\mmdet\apis\inference.py", line 39, in init_detector
    if 'pretrained' in config.model:
  File "F:\Anaconda\Anaconda\envs\openmmlab\lib\site-packages\mmcv\utils\config.py", line 519, in __getattr__
    return getattr(self._cfg_dict, name)
  File "F:\Anaconda\Anaconda\envs\openmmlab\lib\site-packages\mmcv\utils\config.py", line 50, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'model'

### Additional information

AttributeError: 'ConfigDict' object has no attribute 'model'

**Comment by zcablii** [comment]
I'm sorry, but based on the information you have provided, I am unable to determine what the bug is. Please make sure that the installation environment and code used is correct. You can always refer to the official mmrotate [https://github.com/open-mmlab/mmrotate](url) github for more information.
