### ISSUE TITLE
RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.

### ISSUE THREAD

**Issue by fangziy** [zcablii/LSKNet#31]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmrotate/issues) and [Discussions](https://github.com/open-mmlab/mmrotate/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmrotate.readthedocs.io/en/1.x/notes/4_faq.html) but cannot get the expected help.
- [x] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmrotate) or [latest version (1.x)](https://github.com/open-mmlab/mmrotate/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmrotate

### Environment

sys.platform: linux
Python: 3.8.8 (default, Feb 24 2021, 21:46:12) [GCC 7.3.0]
CUDA available: True
GPU 0: NVIDIA GeForce RTX 4090
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.1, V11.1.105
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.8.1
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.9.1
OpenCV: 4.8.0
MMCV: 1.7.1
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.1
MMRotate: 0.3.4+12961ad

### Reproduces the problem - code sample

CUDA_VISIBLE_DEVICES=0 python tools/train.py /root/workspace/Large-Selective-Kernel-Network/configs/lsknet/lsk_t_fpn_1x_dota_le90.py 

### Reproduces the problem - command or script

CUDA_VISIBLE_DEVICES=0 python tools/train.py /root/workspace/Large-Selective-Kernel-Network/configs/lsknet/lsk_t_fpn_1x_dota_le90.py

### Reproduces the problem - error message

RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.

### Additional information

你好，我下载了预训练模型后，想使用您的config文件运行，但是报错了RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.

在同样的环境下，我运行Orien RCNN是不会报错的，请问这是什么问题，应该如何解决呢？

**Comment by zcablii** [comment]
If you train on one single GPU, try to modify the config file to `norm_cfg=dict(type='BN', requires_grad=True)`

**Comment by kobezy** [comment]
> If you train on one single GPU, try to modify the config file to `norm_cfg=dict(type='BN', requires_grad=True)`

Hello author, I am trying to train with single player four cards based on reference/ Tools/dist_ Train. sh ${CONFIG-FILE} ${GPU-NUM} [optional arguments]. My command is/ Tools/dist_ Train.sh./configurations/lsknet/lsk_ S_ FPN_ 3x_ Hrsc_ Le90.py 4, but this issue still occurs: RuntimeError: Default process group has not been initialized, please make sure to call init_ Process_ Group May I ask how I should do it? Thank you.

**Comment by zcablii** [comment]
If you using 4 GPUs, you can set `norm_cfg=dict(type='SyncBN', requires_grad=True)`

**Comment by kobezy** [comment]
After setting up what you said, using 4 GPUs for training still shows this error. How can I solve it? Thank you.
The training command I use is: ./tools/dist_train.sh ./configs/lsknet/lsk_s_fpn_3x_hrsc_le90.py 4  Thank you

**Comment by kobezy** [comment]
> After setting up what you said, using 4 GPUs for training still shows this error. How can I solve it? Thank you.
> The training command I use is: ./tools/dist_train.sh ./configs/lsknet/lsk_s_fpn_3x_hrsc_le90.py 4 Thank you



> If you using 4 GPUs, you can set `norm_cfg=dict(type='SyncBN', requires_grad=True)`

After setting up what you said, using 4 GPUs for training still shows this error. How can I solve it? Thank you.
The training command I use is: ./tools/dist_train.sh ./configs/lsknet/lsk_s_fpn_3x_hrsc_le90.py 4 Thank you
