### ISSUE TITLE
[Bug] TypeError: FormatCode() got an unexpected keyword argument 'verify'

### ISSUE THREAD

**Issue by Pluviophile-sy** [zcablii/LSKNet#42]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmrotate/issues) and [Discussions](https://github.com/open-mmlab/mmrotate/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmrotate.readthedocs.io/en/1.x/notes/4_faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmrotate) or [latest version (1.x)](https://github.com/open-mmlab/mmrotate/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmrotate

### Environment

cuda==11.1
python==3.8.0
torch==1.8.1+cu111
mmcv-full==1.6.0
mmde==2.25.1
mmrotate==0.3.4

### Reproduces the problem - code sample

TypeError: FormatCode() got an unexpected keyword argument 'verify'
subprocess.CalledProcessError: Command '['/root/miniconda3/bin/python', '-u', './LSKNet/tools/train.py', '--local_rank=1', 'LSKNet/configs/lsknet/lsk_s_fpn_1x_dota_le90.py', '--seed', '0', '--launcher', 'pytorch']' returned non-zero exit status 1.

### Reproduces the problem - command or script

 ./LSKNet/tools/dist_train.sh LSKNet/configs/lsknet/lsk_s_fpn_1x_dota_le90.py 2

### Reproduces the problem - error message

More details are shown in the figure below：
![屏幕截图 2024-03-09 185212](https://github.com/zcablii/LSKNet/assets/140753006/d6a4ee7f-db62-4071-a96c-92784e7bd5cc)

### Additional information

1.I'm training a model with an RTX 4090 cloud server, two cards
2.The dataset I'm using is dota v1.0
This is my first time training a model, and I'd love to hear from you to help me solve the problem and point out my shortcomings

**Comment by zcablii** [comment]
Try uninstall 'yapf ' and then pip install yapf==0.40.1

**Comment by Pluviophile-sy** [comment]
> 尝试卸载“yapf”，然后 pip install yapf==0.40.1

According to your approach, this issue has been resolved, much appreciated！
