### ISSUE TITLE
[Docs] Multi-scale train and test about DOTAv1.0

### ISSUE THREAD

**Issue by LeiaJ520** [zcablii/LSKNet#46]
### Branch

master branch  https://mmrotate.readthedocs.io/en/latest/

### 📚 The doc issue

How to train and test multi-scale DOTA data sets? what are the specific commands?

**Comment by zcablii** [comment]
Please refer to [https://github.com/zcablii/LSKNet/tree/main/tools/data/dota](https://github.com/zcablii/LSKNet/tree/main/tools/data/dota)

**Comment by LeiaJ520** [comment]
> Please refer to https://github.com/zcablii/LSKNet/tree/main/tools/data/dota

Hello, I know how to do multi-scale segmentation of DOTA data sets. I want to know how to test the test set. At this time, the test set has images of different scales, how should you select the test results and merge the results to submit to the evaluation server of the DOTA dataset?

**Comment by zcablii** [comment]
> > Please refer to https://github.com/zcablii/LSKNet/tree/main/tools/data/dota
> 
> Hello, I know how to do multi-scale segmentation of DOTA data sets. I want to know how to test the test set. At this time, the test set has images of different scales, how should you select the test results and merge the results to submit to the evaluation server of the DOTA dataset?

Please refer to [docs/en/get_started.md](https://github.com/zcablii/LSKNet/blob/main/docs/en/get_started.md) for testing models and formatting the results for submission. Do not worry about the multi-scale of test data patches, the test time merge function is already defined in [dota.py](https://github.com/zcablii/LSKNet/blob/main/mmrotate/datasets/dota.py).
