### ISSUE TITLE
[Docs] How to set the learning with different number of gpus?

### ISSUE THREAD

**Issue by Diagreen** [zcablii/LSKNet#5]
### Branch

master branch  https://mmrotate.readthedocs.io/en/latest/

### 📚 The doc issue

First of all, it's impressive work for me!. thank you for your repository.
I'm tring to re-generate your result on DOTA v1.0. However, I got the nan loss value during the training.
I'm using dota dataset with multi-scale, and using lsk_s_ema_fpn_1x_dota_le90.py file with 4 gpus.
Based on your comment on line 167, lr=0.0002, #/8*gpu_number, I understood that I need match the value with the different of number of it.
So I set the lr = 0.0004 so that match the same value with 0.0002 on 8 number of gpus, but I got nan loss value on the first epoch.
Maybe I can solve the problem by setting the lower lr value on it, I'm worried that it can be said 're-generation of the paper'.

May I ask you how can I set the appropriate lr on this situation?

**Comment by zcablii** [comment]
Sorry for the confusion in the code comment. The exact relationship should be lr = (your_batchsize) / (default_batchsize) * 0.0002, where default_batchsize is 8 in the provided config file. In your case, lr should be set to 0.0001. If you still get nan, please try an even smaller lr (such as 0.00008 or 0.00005)

**Comment by jsxyhelu** [comment]
On a single A40, set lr=0.0001,Fair1mV2(1024,200 split).I get  the first 8 epochs  map of
 0.248, 0.307, 0.293, 0.310, 0.318, 0.316, 0.339, 0.303, 
I think it has generated bumps, should a smaller lr be set and then retrained?
