### ISSUE TITLE
[Bug] Hi,can u tell me what tools do you use to draw the figure in your paper like Figure 4,thank you

### ISSUE THREAD

**Issue by lzJune** [zcablii/LSKNet#52]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmrotate/issues) and [Discussions](https://github.com/open-mmlab/mmrotate/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmrotate.readthedocs.io/en/1.x/notes/4_faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmrotate) or [latest version (1.x)](https://github.com/open-mmlab/mmrotate/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmrotate

### Environment

![屏幕截图 2024-04-03 180424](https://github.com/zcablii/LSKNet/assets/61384240/fe41691b-c4cd-4950-b06e-121f300edcb9)

### Reproduces the problem - code sample

1

### Reproduces the problem - command or script

1

### Reproduces the problem - error message

1

**Comment by zcablii** [comment]
office PowerPoint

**Comment by CrazyBrick** [comment]
> office PowerPoint
@zcablii 
hi, how do you get the heatmap or featuremap(using mmrotate 0.x)? or just masking on the input images when using PowerPoint?
