### ISSUE TITLE
About where we can get the pretrained weight about the "LSKNet is pretrained on  ImageNet for 100 or 300 epochs" in the article?

### ISSUE THREAD

**Issue by xxxyyynnn** [zcablii/LSKNet#53]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmrotate/issues) and [Discussions](https://github.com/open-mmlab/mmrotate/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmrotate.readthedocs.io/en/1.x/notes/4_faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmrotate) or [latest version (1.x)](https://github.com/open-mmlab/mmrotate/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmrotate

### Environment

pass

### Reproduces the problem - code sample

pass

### Reproduces the problem - command or script

pass

### Reproduces the problem - error message

It seems that I can't find about the checkpoint="/data/pretrained/lsk_s_backbone.pth.tar" in the Codes project.

**Comment by zcablii** [comment]
Imagenet 300-epoch pre-trained LSKNet-T backbone: [Download](https://liveuclac-my.sharepoint.com/:u:/g/personal/zcablii_ucl_ac_uk/EQ_R312q8ihJg1CSwhm80kgBNrxi1CRyLN8vXjF_lAszcA?e=fftQcx)

Imagenet 300-epoch pre-trained LSKNet-S backbone: [Download](https://liveuclac-my.sharepoint.com/:u:/g/personal/zcablii_ucl_ac_uk/EYQMJzI0z0JEtCc-ebVWHbgBftwi0IltLMrbEoQT0qiSzw?e=hm1xKs)

We did not keep the 100 epoch weights.

**Comment by xxxyyynnn** [comment]
Thanks a lot!
