### ISSUE TITLE
[Docs] About HRSC2016 dataset

### ISSUE THREAD

**Issue by LeiaJ520** [zcablii/LSKNet#56]
### Branch

master branch  https://mmrotate.readthedocs.io/en/latest/

### 📚 The doc issue

The HRSC2016 dataset is a multilevel classified data set, consisting of 3 major classes and 27 subclasses. I would like to ask the author in what categories are the mAP results of HRSC2016 data set presented in the paper?

**Comment by zcablii** [comment]
single class as reported in other related work

**Comment by LeiaJ520** [comment]
Does it mean that all categories of objects in HRSC2016 are processed as one category, which is 'ship'? May I ask if the author could kindly share the processed dataset?

**Comment by zcablii** [comment]
Yes. The default 'HRSCDataset' dataset class and config files are already set for the single category detection.

**Comment by zcablii** [comment]
You do not need to perform pre-processing.

**Comment by LeiaJ520** [comment]
Thank you for your answer, re-read the data set configuration file and understand your practice. Because I wanted a single class of HRSC2016 data set for my own study, I wanted to ask how your data set was handled.
