### ISSUE TITLE
[split] 

### ISSUE THREAD

**Issue by LW091** [zcablii/LSKNet#60]
### What's the feature?

The gap between multi-core processing and single-core processing is different, and is the gap for multi-core processing 500?

**Comment by zcablii** [comment]
ms stands for multi-scale, not multi-core. And yes, multi-scale splitting is adopting a gap of 500.

**Comment by LW091** [comment]
> ms stands for multi-scale, not multi-core. And yes, multi-scale splitting is adopting a gap of 500.

Okay, I see, thanks for your answer
