### ISSUE TITLE
how can I prepare the Potsdam or Vaihingen datasets

### ISSUE THREAD

**Issue by wxy16** [zcablii/LSKNet#62]
### What's the feature?

Hello, how can I prepare the Potsdam or Vaihingen datasets to reproduce the results of a paper? There are too many files available for download on the official website, and I lack experience in handling these datasets. Thank you for your assistance.

**Comment by zcablii** [comment]
Thank you for your remainder. We updated the README to share the prepared datasets.


> To facilitate easy reproduction and swift initiation for beginners, we offer our prepared remote sensing segmentation datasets here.
> [Vaihingen](https://pan.baidu.com/s/1SjOaZ55rUlghoggBcV1GCA?pwd=rssg)
> [Potsdam](https://pan.baidu.com/s/1yihagJKRDs_9i2qrI2Lh4Q?pwd=rssg)
> [LoveDA](https://pan.baidu.com/s/1OkeOrVQ1kvoxF7zYCdKz1Q?pwd=rssg)
> [uavid](https://pan.baidu.com/s/1FEvaU41Ay6D5Js7QwD4CGQ?pwd=rssg)

**Comment by wxy16** [comment]
Good work! Thank you.
