### ISSUE TITLE
带有大的增长卷积核和增长膨胀率的深度可分离卷积

### ISSUE THREAD

**Issue by ssfkfffddj** [zcablii/LSKNet#64]
### Branch

master branch  https://mmrotate.readthedocs.io/en/latest/

### 📚 The doc issue

您好！非常感谢您能够分享LskNet的源码。
在阅读LskNet的论文时，我遇到一些问题想跟您咨询一下：论文中提到“Therefore, we propose to construct a larger kernel convolution by explicitly decomposing it into a sequence of depth-wise convolutions with a large growing kernel and increasing dilation.”深度可分离卷积的核的尺寸和膨胀率都是增长的，但是代码中卷积核的尺寸和膨胀率都是不变的。
请问一下卷积核的尺寸和膨胀率的增长应该怎么理解？
非常感谢您的解答！

**Comment by zcablii** [comment]
"Larger kernel convolution by explicitly decomposing it into a sequence of depth-wise convolutions", for example, the large kernel is decomposed into a conv k=5, d=1 and a conv k=7, d=3. 
Here, k 5->7 is "growing kernel" and d 1->3 is "increasing dilation"

**Comment by ssfkfffddj** [comment]
我理解了，非常感谢您的讲解！
