### ISSUE TITLE
which py files are necessary for the inference?

### ISSUE THREAD

**Issue by jiofgnuo** [zcablii/LSKNet#65]
### What's the feature?

I would like to use this model for region proposal as part of a two-stage segmentation model. My segmentation model is built on mmsegmentation, and using command line inference will cause conflicts. Could you please point out which .py files are necessary for the inference part so as to facilitate the integration of the two models.

**Comment by zcablii** [comment]
LSKNet is a backbone model. If you want to use LSKNet as a backbone in your segmenter, you can refer to [this](https://github.com/zcablii/LSKNet/blob/main/mmrotate/models/backbones/lsknet.py) file. But you have to make some adaptations to mmsegmentation framework.

**Comment by jiofgnuo** [comment]
Thanks a lot！
