### ISSUE TITLE
RuntimeError: Unable to find a valid cuDNN algorithm to run convolution

### ISSUE THREAD

**Issue by lsjEric** [zcablii/LSKNet#67]
### What's the feature?

I have two 4090 graphics cards. When I run the code with the first graphics card, there is no problem, but when I use the second graphics card, the above error appears. I would like to ask the following authors if they have encountered this problem.

**Comment by zcablii** [comment]
Based on [this answer](https://stackoverflow.com/questions/61467751/unable-to-find-a-valid-cudnn-algorithm-to-run-convolution), try a smaller model or a smaller batch size? Or you can find more solutions on Google, because this is likely not the issue of this repo.
