### ISSUE TITLE
Model deploy

### ISSUE THREAD

**Issue by quxianjiuguo** [zcablii/LSKNet#70]
### What's the feature?

I followed your readme file，and now I got a robust model weight。 I would like to deploy it on web service。  Is there any guides to complete it ？

**Comment by zcablii** [comment]
Sorry, I am not familiar with website development. Maybe you can get some clues from [mmdepoly](https://github.com/open-mmlab/mmdeploy).

**Comment by niupihhhh** [comment]
What folder is your model in?
