### ISSUE TITLE
[Docs] 

### ISSUE THREAD

**Issue by daihaoma** [zcablii/LSKNet#72]
### Branch

master branch  https://mmrotate.readthedocs.io/en/latest/

### 📚 The doc issue

Thanks to the authors for their research. Can you please tell me if  used any other preprocessing besides splitting the dataset before training. I trained the project with dota dataset and found that the map value is only 0.59. and the best training occurs at epoch10. i checked the labeled boxes during training and found that a part of them is not oriented (Fig.). Is this normal? Here's my log.
![P0002__1024__0___0](https://github.com/zcablii/LSKNet/assets/156630537/dfcafbef-db68-41cd-89ba-478ce23d2ffe)
![P0002__1024__0___824](https://github.com/zcablii/LSKNet/assets/156630537/48946565-668f-430c-a8d4-9c80fe5cbde9)
![P0002__1024__1533___0](https://github.com/zcablii/LSKNet/assets/156630537/e196ba2a-3ccb-4b57-8029-e2f1901b785c)
[20240701_164416.log](https://github.com/user-attachments/files/16076105/20240701_164416.log)

**Comment by zcablii** [comment]
1. Make sure you are using multi-scale splitting for training[ms_train.json](https://github.com/zcablii/LSKNet/blob/main/tools/data/dota/split/split_configs/ms_train.json) and testing[ms_test.json](https://github.com/zcablii/LSKNet/blob/main/tools/data/dota/split/split_configs/ms_test.json)
2. It looks like you are using single GPU with bs=1. You may need to adjust your lr and bs accordingly. #43

**Comment by daihaoma** [comment]
> 1. 确保使用多尺度分割来训练[ms_train.json](https://github.com/zcablii/LSKNet/blob/main/tools/data/dota/split/split_configs/ms_train.json)并测试[ms_test.json](https://github.com/zcablii/LSKNet/blob/main/tools/data/dota/split/split_configs/ms_test.json)
> 2. 看起来您正在使用单个 GPU，并且 bs=1。您可能需要相应地调整 lr 和 bs。[[shceduler] ](https://github.com/zcablii/LSKNet/issues/43)[ #43](https://github.com/zcablii/LSKNet/issues/43)[](https://github.com/zcablii/LSKNet/issues/43)
Thanks for your reply, I will re change my lr and bs. i refer to your reply to know that lr = (your_batchsize) / (default_batchsize) * 0.0002. i have only one gpu so is default_batchsize equal to 1 here.

**Comment by daihaoma** [comment]
> 1. 确保使用多尺度分割来训练[ms_train.json](https://github.com/zcablii/LSKNet/blob/main/tools/data/dota/split/split_configs/ms_train.json)并测试[ms_test.json](https://github.com/zcablii/LSKNet/blob/main/tools/data/dota/split/split_configs/ms_test.json)
> 2. 看起来您正在使用单个 GPU，并且 bs=1。您可能需要相应地调整 lr 和 bs。[[shceduler] ](https://github.com/zcablii/LSKNet/issues/43)[ #43](https://github.com/zcablii/LSKNet/issues/43)[](https://github.com/zcablii/LSKNet/issues/43)
Thanks for your reply, I will re change my lr and bs. i refer to your reply to know that lr = (your_batchsize) / (default_batchsize) * 0.0002. i have only one gpu so is default_batchsize equal to 1 here.
