### ISSUE TITLE
[Feature] 您好，读了好几遍您的LSK论文，其中最大的疑惑是怎么实现select的。 在代码中，就是将sig分成的两份，然后和不同尺度相乘，第一个sig和attn1相乘，第二个sig和attn2相乘，这是如何体现选择的？

### ISSUE THREAD

**Issue by 23jisuper** [zcablii/LSKNet#73]
### What's the feature?

select

**Comment by zcablii** [comment]
第一个sig可以理解为是对第一支feature上做空间上的选择，第二个sig是对另一支feature做空间选择。

**Comment by 23jisuper** [comment]
> 第一个sig可以理解为是对第一支feature上做空间上的选择，第二个sig是对另一支feature做空间选择。

感谢您的的回复，这种选择是自适应的吗？  我的理解是sig中的两个通道好像并没有区分分支来说明sig[0]对应第一个分支、sig[1]对应第二个分支？还是说作者您是通过对比实验来验证attn1*sig[0]+attn2*sig[1]比attn1*sig[1]+attn2*sig[0]效果更好？

**Comment by zcablii** [comment]
sig[0]和sig[1]是只不过是attetion出来的两个channel，地位是等价的，所以从模型设计的角度讲，attn1sig[0]+attn2sig[1]和attn1sig[1]+attn2sig[0]是完全一样的。

**Comment by 23jisuper** [comment]
> sig[0]和sig[1]是只不过是attetion出来的两个channel，地位是等价的，所以从模型设计的角度讲，attn1sig[0]+attn2sig[1]和attn1sig[1]+attn2sig[0]是完全一样的。

您论文的主要思想就是针对不同目标采用不同感受野来提取特征，再结合您论文Figure 5也体现出了您的思想。在Figure 5中较小的目标与5*5的输出相乘，较大的与7*7的输出相乘，我理解了您图中所表达的select。代码中attn = attn1 * sig[:,0,:,:].unsqueeze(1) + attn2 * sig[:,1,:,:].unsqueeze(1)是如何体现select思想的还不能很好的理解，按代码中的逻辑理解sig[0]代表的是否就是小感受野矩阵，sig[1]就代表了大感受野的注意力矩阵？

**Comment by zcablii** [comment]
是的。如果对选择性机制有不理解的地方，欢迎结合阅读我们之前的工作：Li, Xiang, Wenhai Wang, Xiaolin Hu, and Jian Yang. "Selective kernel networks." In Proceedings of the IEEE/CVF conference on computer vision and pattern recognition, pp. 510-519. 2019.

**Comment by 23jisuper** [comment]
> 是的。如果对选择性机制有不理解的地方，欢迎结合阅读我们之前的工作：Li, Xiang, Wenhai Wang, Xiaolin Hu, and Jian Yang. "Selective kernel networks." In Proceedings of the IEEE/CVF conference on computer vision and pattern recognition, pp. 510-519. 2019.

好的，感谢您的答复！
