### ISSUE TITLE
使用单卡训练时报错

### ISSUE THREAD

**Issue by adii-t** [zcablii/LSKNet#76]
### Branch

master branch  https://mmrotate.readthedocs.io/en/latest/

### 📚 The doc issue

可能是代码内部强制要分布式处理，所以我单卡运行时报错：
RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.
我设置了--launcher=none gpus=1,还是会报错，请问还应该修改哪部分代码呢？

**Comment by zcablii** [comment]
change 'SyncBN' to 'BN'

**Comment by adii-t** [comment]
解决了 谢谢哥！
