### ISSUE TITLE
训练LSKNet-T时map显示为0

### ISSUE THREAD

**Issue by SMDR1412** [zcablii/LSKNet#77]
### Branch

master branch  https://mmrotate.readthedocs.io/en/latest/

### 📚 The doc issue

我在训练LSKNet网络时训练多轮MAP一直显示为0，用其他模型训练不会出现这样的问题

**Comment by zcablii** [comment]
根据您提供的信息我无法判断是什么问题。建议检查配置文件，数据集和与训练权重加载是否都正确无误。
