### ISSUE TITLE
[Docs] 请问单卡训练的话，需要改什么参数吗

### ISSUE THREAD

**Issue by 921162820** [zcablii/LSKNet#80]
### Branch

master branch  https://mmrotate.readthedocs.io/en/latest/

### 📚 The doc issue

比如custom_hooks=[dict(
        type='ExpMomentumEMAHook',
        total_iter = 8541*12,
        priority=49)
    ]

optimizer = dict(
    _delete_=True,
    type='AdamW',
    lr=0.0002, #/8*gpu_number,
    betas=(0.9, 0.999),
    weight_decay=0.05)这里的参数，单卡训练的话需要怎么改呀

**Comment by zcablii** [comment]
可以根据你的batch size使用适当的lr。

**Comment by 921162820** [comment]
请问训练自己的数据集的话，怎么做呢，是按哪个数据集来设置标注呢

**Comment by zcablii** [comment]
建议使用mmrotate已经支持的数据集的标注格式，这样改起来更方便。

**Comment by 921162820** [comment]
感谢大佬指点，请问custom_hooks=[dict(
type='ExpMomentumEMAHook',
total_iter = 8541*12,
priority=49)
]这里的total_iter 我该如何修改呢，比如我的训练图片个数是8000，epoch是12的情况下，total_iter 该怎么写呢

**Comment by zcablii** [comment]
一个epoch的iteration数量 = 总图片数量 / batch_size。
total_iter = 总epoch数 * 一个epoch的iteration数量

**Comment by zcablii** [comment]
8541不是总图片数，是一个epoch的iteration数量。

**Comment by 921162820** [comment]
> 8541不是总图片数，是一个epoch的iteration数量。

请问一个epoch的iteration数量= 总图片数/batch嘛

**Comment by zcablii** [comment]
> 一个epoch的iteration数量 = 总图片数量 / batch_size。 total_iter = 总epoch数 * 一个epoch的iteration数量

是的

**Comment by 921162820** [comment]
> 8541不是总图片数，是一个epoch的iteration数量。

您config中的batch为1，我的dota图片数目为15749，请问大佬，8541是怎么得到的呀，难道您的dota图片数目是8541张嘛

**Comment by zcablii** [comment]
8卡跑的，所以batch_size相当于8。我是multiscale的数据切分，一共68,000+图。

**Comment by 921162820** [comment]
> multiscale
谢谢大佬指点，请问单尺度和多尺度切分，哪种跑出来的结果更高呀，有什么区别呀

**Comment by zcablii** [comment]
当然多尺度结果更高
