### ISSUE TITLE
[Docs] 关于模型训练过程中的一些细节问题

### ISSUE THREAD

**Issue by wap1024** [zcablii/LSKNet#81]
### Branch

master branch  https://mmrotate.readthedocs.io/en/latest/

### 📚 The doc issue

您好，作者，我想请问您一下，关于训练过程中对于模型权重的保存是保存最后一个权重？还是验证集中最好的那个呢？期待您的回答，谢谢。

**Comment by zcablii** [comment]
只用最后一个epoch的权重。

**Comment by wap1024** [comment]
好的，十分感谢您的回复，祝您生活愉快！
















在 2024-09-11 11:33:12，"Yuxuan Li" ***@***.***> 写道：

只用最后一个epoch的权重。
