### ISSUE TITLE
关于acc

### ISSUE THREAD

**Issue by ocrhei** [zcablii/LSKNet#82]
### What's the feature?

Epoch [1][100/7565]	lr: 1.861e-04, eta: 15:27:17, time: 0.171, data_time: 0.004, memory: 4054, loss_rpn_cls: 0.0701, loss_rpn_bbox: 0.0420, loss_cls: 0.0402, acc: 99.4526, loss_bbox: 0.0244, loss: 0.1767, grad_norm: 1.3728。

作者您好，请问log里的acc是什么意思呢，在第100次迭代，它的值就是99了，感觉不科学。

**Comment by zcablii** [comment]
see [here](https://github.com/open-mmlab/mmdetection/issues/5939)

**Comment by ocrhei** [comment]
感谢指点，请问损失降到多少差不多就可以了呢，我看第100次迭代的loss就loss: 0.1767了，感觉很小

**Comment by zcablii** [comment]
loss大大小不能看绝对的数值，要看相对的值。如果继续训练，loss还会持续下降。
