### ISSUE TITLE
训练自己的数据集

### ISSUE THREAD

**Issue by ocrhei** [zcablii/LSKNet#83]
### Branch

master branch  https://mmrotate.readthedocs.io/en/latest/

### 📚 The doc issue

作者您好，当我训练自己的数据集的时候，不加ema，结果正常，但是加了ema之后，掉电特别多，map只要30多，请问这该如何解决呢

**Comment by zcablii** [comment]
ema需要适当加长训练轮数，因为ema非常的慢热

**Comment by ocrhei** [comment]
> ema需要适当加长训练轮数，因为ema非常的慢热

感谢指点，但是我看开与不开ema，损失值都差不多哎，稳定0.13左右。 其次就是感觉损失降低的很小，刚开始损失就是0.18左右，请问损失权重需要增大一些吗

**Comment by zcablii** [comment]
当然loss都会差不多，因为加不加ema都是训练的同一个模型，区别在于ema会额外通过平滑加权去维护另外一个模型的权重，用于测试。

**Comment by ocrhei** [comment]
作者您好，请问我如果想训练FAIR1M或者ssdd等数据集，还需要对训练数据集进行切分吗，但是我看只有dota数据集的切分代码哎

**Comment by zcablii** [comment]
ssdd不用切，FAIR1M需要根据论文中的方式切分。可以使用[这个](https://github.com/zcablii/LSKNet/tree/main/tools/data/fair)工具进行fair1m<-->dota格式的转换和切分。

**Comment by ocrhei** [comment]
作者您好，请问如果把您代码中的损失换成kfiou损失，会有精度提升吗

**Comment by zcablii** [comment]
kfiou主要是用在单阶段检测框架上的。如果是LSKNet+单阶段检测器+kfiou，预期是比resnet+单阶段检测器+kfiou的性能要高的

**Comment by ocrhei** [comment]
> kfiou主要是用在单阶段检测框架上的。如果是LSKNet+单阶段检测器+kfiou，预期是比resnet+单阶段检测器+kfiou的性能要高的

感谢大佬指点，还有最后一个小小的困惑，就是为什么kfiou在双阶段检测框架上不流行呀

**Comment by zcablii** [comment]
个人认为：
我做的实验表明，单阶段检测器的mAP@75往往远低于双阶段的，而@50却差的不多，意味着单阶段模型对框的角度回归效果往往远不如二阶段的。所以GWD， KLD等一些列loss在单阶段检测器上就比较有用武之地。双阶段模型往往对旋转框的回归会好很多，所以用这些loss几乎没有进一步的性能提升。

**Comment by ocrhei** [comment]
> 个人认为： 我做的实验表明，单阶段检测器的mAP@75往往远低于双阶段的，而@50却差的不多，意味着单阶段模型对框的角度回归效果往往远不如二阶段的。所以GWD， KLD等一些列loss在单阶段检测器上就比较有用武之地。双阶段模型往往对旋转框的回归会好很多，所以用这些loss几乎没有进一步的性能提升。

感谢指点，我没问题了
