### ISSUE TITLE
DOTA1.0数据集 

### ISSUE THREAD

**Issue by Joey-He** [zcablii/LSKNet#84]
### Model/Dataset/Scheduler description

请问dota数据集官网没有提供test集合中的标注信息，但官方还提供了test的分割的json，可以从哪里获取呢？，还是说实验中使用的val结果作为评估map标准呢？

### Open source status

- [ ] The model implementation is available
- [ ] The model weights are available.

**Comment by zcablii** [comment]
[DOTA官网线上评测： [http://bed4rs.net:8001/evaluation1/](http://bed4rs.net:8001/evaluation1/)
