### ISSUE TITLE
[Bug] Very low speed problem in inference detector

### ISSUE THREAD

**Issue by AliSharififar** [zcablii/LSKNet#85]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmrotate/issues) and [Discussions](https://github.com/open-mmlab/mmrotate/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmrotate.readthedocs.io/en/1.x/notes/4_faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmrotate) or [latest version (1.x)](https://github.com/open-mmlab/mmrotate/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmrotate

### Environment

sys.platform: win32
Python: 3.8.18 (default, Sep 11 2023, 13:39:12) [MSC v.1916 64 bit (AMD64)]
CUDA available: True
GPU 0: NVIDIA GeForce RTX 3070 Ti
CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1
NVCC: Cuda compilation tools, release 11.1, V11.1.74

### Reproduces the problem - code sample

```
def main(args):
    # build the model from a config file and a checkpoint file
    model = init_detector(args.config, args.checkpoint, device=args.device)
    # test a single image

    result = inference_detector(model, args.img)

    # show the results
    show_result_pyplot(
        model,
        args.img,
        result,
        palette=args.palette,
        score_thr=args.score_thr,
        out_file=args.out_file)
```

### Reproduces the problem - command or script

1

### Reproduces the problem - error message

1

### Additional information

I have read your article completely, it has achieved excellent performance in accuracy.I use model for DOTA dataset.
But I encountered a problem, when I run image_demo.py file, the performance speed in this part 
result = inference_detector(model, args.img) 
takes 3.5 seconds for an image with size 1024*890. I set the model on Cuda. No matter what I did to improve the speed, I could not.
Please guide me
thank you very much

**Comment by zcablii** [comment]
The 3.5s likely includes the time taken for Python package imports, model weight loading, and model inference. I believe the package imports account for the majority of the time.

**Comment by AliSharififar** [comment]
> The 3.5s likely includes the time taken for Python package imports, model weight loading, and model inference. I believe the package imports account for the majority of the time.

the model weight loading in this line:
model = init_detector(args.config, args.checkpoint, device=args.device)
but feature extraction happen in this line and According to the reviews I made, no weight is loaded in this part:
    t1= time.time()
    result = inference_detector(model, args.img)
    print(time.time()-t1)

**Comment by zcablii** [comment]
If you want to get the inference speed, I recommend you use the tools/test.py for batch inference.

**Comment by AliSharififar** [comment]
> If you want to get the inference speed, I recommend you use the tools/test.py for batch inference.

thank you for your help. I tested the model with tools/test.py file. but it couldn't calculated FPS just it give me a file that include images name and...
my os is windows

**Comment by zcablii** [comment]
during the inference, the fps will show at the end of the progress bar.
