### ISSUE TITLE
Training time

### ISSUE THREAD

**Issue by OE-jimvanoosten** [zcablii/LSKNet#86]
### Branch

master branch  https://mmrotate.readthedocs.io/en/latest/

### 📚 The doc issue

Relatively new to computer vision. Noob question incoming: how is it possible that Oriented R-CNN + LSKNet has fewer parameters and fewer GFLOPS that Oriented R-CNN + ResNet50, but still LSKNet takes twice as long to train???

### Suggest a potential alternative/fix

Let me know. Appreciate it.

**Comment by zcablii** [comment]
The Adam optimizer takes much more memory and time than the SGD optimizer.

**Comment by OE-jimvanoosten** [comment]
Are you sure? When I train Oriented R-CNN + ResNet50 + Adam optimizer, LSKNet is still twice as slow!

**Comment by zcablii** [comment]
Another important reason is the use of dilated convolutions. Dilated convolutions lead to discontinuous memory access and cache miss issues. For some current GPUs and deep learning framework operators, there may not be specific optimizations for dilated convolutions, but it is said that optimizations will be introduced later.
