### ISSUE TITLE
[Bug] RuntimeError: Default process group has not been initialized, please make sure to call init_process_group

### ISSUE THREAD

**Issue by lixinru77** [zcablii/LSKNet#87]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmrotate/issues) and [Discussions](https://github.com/open-mmlab/mmrotate/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmrotate.readthedocs.io/en/1.x/notes/4_faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmrotate) or [latest version (1.x)](https://github.com/open-mmlab/mmrotate/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmrotate

### Environment

# packages in environment at /home/lixinru/anaconda3/envs/lsknet:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
addict                    2.4.0                    pypi_0    pypi
aliyun-python-sdk-core    2.16.0                   pypi_0    pypi
aliyun-python-sdk-kms     2.16.5                   pypi_0    pypi
ca-certificates           2024.9.24            h06a4308_0  
certifi                   2024.8.30                pypi_0    pypi
cffi                      1.17.1                   pypi_0    pypi
charset-normalizer        3.4.0                    pypi_0    pypi
click                     8.1.7                    pypi_0    pypi
colorama                  0.4.6                    pypi_0    pypi
contourpy                 1.1.1                    pypi_0    pypi
crcmod                    1.7                      pypi_0    pypi
cryptography              43.0.3                   pypi_0    pypi
cycler                    0.12.1                   pypi_0    pypi
e2cnn                     0.2.3                    pypi_0    pypi
filelock                  3.14.0                   pypi_0    pypi
fonttools                 4.55.0                   pypi_0    pypi
fsspec                    2024.10.0                pypi_0    pypi
huggingface-hub           0.26.2                   pypi_0    pypi
idna                      3.10                     pypi_0    pypi
importlib-metadata        8.5.0                    pypi_0    pypi
importlib-resources       6.4.5                    pypi_0    pypi
jmespath                  0.10.0                   pypi_0    pypi
kiwisolver                1.4.7                    pypi_0    pypi
ld_impl_linux-64          2.40                 h12ee557_0  
libffi                    3.4.4                h6a678d5_1  
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libstdcxx-ng              11.2.0               h1234567_1  
markdown                  3.7                      pypi_0    pypi
markdown-it-py            3.0.0                    pypi_0    pypi
matplotlib                3.7.5                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
mmcv-full                 1.7.2                    pypi_0    pypi
mmdet                     2.28.2                   pypi_0    pypi
mmrotate                  0.3.4                     dev_0    <develop>
model-index               0.1.11                   pypi_0    pypi
mpmath                    1.3.0                    pypi_0    pypi
ncurses                   6.4                  h6a678d5_0  
numpy                     1.24.4                   pypi_0    pypi
opencv-python             4.10.0.84                pypi_0    pypi
opendatalab               0.0.10                   pypi_0    pypi
openmim                   0.3.9                    pypi_0    pypi
openssl                   3.0.15               h5eee18b_0  
openxlab                  0.1.2                    pypi_0    pypi
ordered-set               4.1.0                    pypi_0    pypi
oss2                      2.17.0                   pypi_0    pypi
packaging                 24.2                     pypi_0    pypi
pandas                    2.0.3                    pypi_0    pypi
pillow                    10.4.0                   pypi_0    pypi
pip                       24.2             py38h06a4308_0  
platformdirs              4.3.6                    pypi_0    pypi
pycocotools               2.0.7                    pypi_0    pypi
pycparser                 2.22                     pypi_0    pypi
pycryptodome              3.21.0                   pypi_0    pypi
pygments                  2.18.0                   pypi_0    pypi
pyparsing                 3.1.4                    pypi_0    pypi
python                    3.8.20               he870216_0  
python-dateutil           2.9.0.post0              pypi_0    pypi
pytz                      2023.4                   pypi_0    pypi
pyyaml                    6.0.2                    pypi_0    pypi
readline                  8.2                  h5eee18b_0  
requests                  2.28.2                   pypi_0    pypi
rich                      13.4.2                   pypi_0    pypi
safetensors               0.4.5                    pypi_0    pypi
scipy                     1.10.1                   pypi_0    pypi
setuptools                60.2.0                   pypi_0    pypi
shapely                   2.0.6                    pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
sqlite                    3.45.3               h5eee18b_0  
sympy                     1.13.3                   pypi_0    pypi
tabulate                  0.9.0                    pypi_0    pypi
terminaltables            3.1.10                   pypi_0    pypi
timm                      1.0.11                   pypi_0    pypi
tk                        8.6.14               h39e8969_0  
tomli                     2.1.0                    pypi_0    pypi
torch                     1.8.0+cu111              pypi_0    pypi
torchaudio                0.8.0                    pypi_0    pypi
torchvision               0.9.0+cu111              pypi_0    pypi
tqdm                      4.65.2                   pypi_0    pypi
typing-extensions         4.12.2                   pypi_0    pypi
tzdata                    2024.2                   pypi_0    pypi
urllib3                   1.26.20                  pypi_0    pypi
wheel                     0.44.0           py38h06a4308_0  
xz                        5.4.6                h5eee18b_1  
yapf                      0.43.0                   pypi_0    pypi
zipp                      3.20.2                   pypi_0    pypi
zlib                      1.2.13               h5eee18b_1  

### Reproduces the problem - code sample

Traceback (most recent call last):
  File "tools/train.py", line 192, in <module>
    main()
  File "tools/train.py", line 181, in main
    train_detector(
  File "/media/newmy/code_env/LSKNet-main/mmrotate/apis/train.py", line 141, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/lixinru/anaconda3/envs/lsknet/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 136, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/lixinru/anaconda3/envs/lsknet/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 53, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/home/lixinru/anaconda3/envs/lsknet/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 31, in run_iter
    outputs = self.model.train_step(data_batch, self.optimizer,
  File "/home/lixinru/anaconda3/envs/lsknet/lib/python3.8/site-packages/mmcv/parallel/data_parallel.py", line 77, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/lixinru/anaconda3/envs/lsknet/lib/python3.8/site-packages/mmdet/models/detectors/base.py", line 248, in train_step
    losses = self(**data)
  File "/home/lixinru/anaconda3/envs/lsknet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/lixinru/anaconda3/envs/lsknet/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 119, in new_func
    return old_func(*args, **kwargs)
  File "/home/lixinru/anaconda3/envs/lsknet/lib/python3.8/site-packages/mmdet/models/detectors/base.py", line 172, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/media/newmy/code_env/LSKNet-main/mmrotate/models/detectors/two_stage.py", line 127, in forward_train
    x = self.extract_feat(img)
  File "/media/newmy/code_env/LSKNet-main/mmrotate/models/detectors/two_stage.py", line 67, in extract_feat
    x = self.backbone(img)
  File "/home/lixinru/anaconda3/envs/lsknet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/media/newmy/code_env/LSKNet-main/mmrotate/models/backbones/lsknet.py", line 219, in forward
    x = self.forward_features(x)
  File "/media/newmy/code_env/LSKNet-main/mmrotate/models/backbones/lsknet.py", line 209, in forward_features
    x, H, W = patch_embed(x)
  File "/home/lixinru/anaconda3/envs/lsknet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/media/newmy/code_env/LSKNet-main/mmrotate/models/backbones/lsknet.py", line 125, in forward
    x = self.norm(x)        
  File "/home/lixinru/anaconda3/envs/lsknet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/lixinru/anaconda3/envs/lsknet/lib/python3.8/site-packages/torch/nn/modules/batchnorm.py", line 537, in forward
    world_size = torch.distributed.get_world_size(process_group)
  File "/home/lixinru/anaconda3/envs/lsknet/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 715, in get_world_size
    return _get_group_size(group)
  File "/home/lixinru/anaconda3/envs/lsknet/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 267, in _get_group_size
    default_pg = _get_default_group()
  File "/home/lixinru/anaconda3/envs/lsknet/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 351, in _get_default_group
    raise RuntimeError("Default process group has not been initialized, "
RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.

### Reproduces the problem - command or script

python tools/train.py ./configs/lsknet/lsk_s_fpn_1x_dota_le90.py

### Reproduces the problem - error message

in th  /home/anaconda3/envs/lsknet/lib/python3.8/site-packages/torch/nn/modules/batchnorm.py
        assert self.running_mean is None or isinstance(self.running_mean, torch.Tensor)
        assert self.running_var is None or isinstance(self.running_var, torch.Tensor)
        running_mean = self.running_mean if not self.training or self.track_running_stats else None
        running_var = self.running_var if not self.training or self.track_running_stats else None

        need_sync = bn_training
        if need_sync:
            process_group = torch.distributed.group.WORLD
            if self.process_group:
                process_group = self.process_group
            world_size = torch.distributed.get_world_size(process_group)
            # print(world_size)
            need_sync = world_size > 1
and the /home/lixinru/anaconda3/envs/lsknet/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py
def get_world_size(group=None):
    """
    Returns the number of processes in the current process group

    Args:
        group (ProcessGroup, optional): The process group to work on. If None,
            the default process group will be used.

    Returns:
        The world size of the process group
        -1, if not part of the group

    """
    if _rank_not_in_group(group):
        return -1

    return _get_group_size(group)

### Additional information

这应该是在backbone训练时候，提取特征调用到了 x = self.norm(x) ，然后在这个函数的forward调用了分布式训练函数world_size = torch.distributed.get_world_size(process_group)，由于我的电脑是4090单卡机，并不能进行分布式训练所以报错。我想询问怎么修改这里的代码才能使用单卡机训练。我尝试将 SyncBatchNorm里面的分布式训练删除，但是后面又调用了这个函数，我无法解决这个问题，希望您可以给予帮助，感谢！！！

Here is the translation of your text into English:
This should be during the training of the backbone, where the feature extraction calls x = self.norm(x), and then this function's forward call is made to the distributed training function world_size = torch.distributed.get_world_size(process_group). Since my computer is a single-card 4090 machine, I cannot perform distributed training, so I encountered an error. I would like to ask how to modify this code to train with a single-card machine. I tried to remove the distributed training from SyncBatchNorm, but this function was called again later, and I couldn't solve this problem. I hope you can help, thank you very much!!!

**Comment by zcablii** [comment]
change 'SyncBN' to 'BN'

**Comment by lixinru77** [comment]
但是我好像没有找到直接调用SyncBN这个函数的代码，好像只有这里调用：x=self.norm(x)

li同学
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zcablii/LSKNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月19日(星期二) 中午12:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zcablii/LSKNet] [Bug] RuntimeError: Default process group has not been initialized, please make sure to call init_process_group (Issue #87)





 
change 'SyncBN' to 'BN'

**Comment by zcablii** [comment]
change 'SyncBN' to 'BN' in the config file
