### ISSUE TITLE
[Docs] FAIR1M 1.0

### ISSUE THREAD

**Issue by Huyifan626** [zcablii/LSKNet#88]
### Branch

master branch  https://mmrotate.readthedocs.io/en/latest/

### 📚 The doc issue

How to convert the FAIR1M 1.0 dataset format into the DOTA dataset format please?

**Comment by zcablii** [comment]
Please refer to the tools [here](https://github.com/zcablii/LSKNet/blob/main/tools/data/fair/fair_to_dota.py)

**Comment by Huyifan626** [comment]
Thank you for your reply!

**Comment by zcablii** [comment]
You need to format the test results and submit on the [test server](https://www.gaofen-challenge.com/benchmark).

**Comment by Huyifan626** [comment]
"Does your code implement the functionality you mentioned above? I have downloaded the model weight file you provided. Is the test command 'python tools/test.py configs/lsknet/lsk_s_fpn_1x_fair_le90.py lsknet_s_fair_epoch12.pth --format-only' correct? Can it output the correct results that can be submitted on the test server?"

**Comment by zcablii** [comment]
your environment is not properly installed. You should install pytorch version capable with your RTX3090. Moreover, with the output result, you may refer to the example conversion code [here](https://github.com/zcablii/LSKNet/blob/main/tools/data/fair/dota_to_fair.py) to convert the results.

**Comment by Huyifan626** [comment]
When performing inference, do the test set images need to be cropped? Do they need to be converted to PNG format?I am currently using the original uncropped test set in TIFF format. When I run the command “CUDA_VISIBLE_DEVICES=1 python tools/test.py configs/lsknet/lsk_s_fpn_1x_fair_le90.py lsknet_s_fair_epoch12.pth --out results.pkl --format-onl”.I get the error message shown in the screenshot.
![image](https://github.com/user-attachments/assets/6461065f-b400-4391-9719-326f62e94d84)

**Comment by Huyifan626** [comment]
Is the --eval parameter required?When I crop the dataset like DOTA does，the issue is still not resolved.Are there any other settings that need to be configured?
![image](https://github.com/user-attachments/assets/0ccfc339-3821-4a93-b411-eb03e98222a9)

**Comment by Huyifan626** [comment]
![image](https://github.com/user-attachments/assets/e7cbc090-e238-481c-9d5a-85c8ad61ecd5)

**Comment by zcablii** [comment]
It seems that you did not pass the correct dataset path in the config file. Please check your config file.

**Comment by Huyifan626** [comment]
![image](https://github.com/user-attachments/assets/2a48d7f5-6310-4c29-98e2-772a0ebc65be)
Have you ever meet this question?

**Comment by zcablii** [comment]
your zipped folder may not strictly follow the submission requirement.

**Comment by Huyifan626** [comment]
Thank you for your reply!But there is another question that the result of mAP is 45.44 rather than 47.87 in your paper.I just change the config file from "lsk_s_fpn_1x_dota_le90" to "lsk_s_fpn_1x_fair_le90".Does this change lead to the 45.44 result?
![image](https://github.com/user-attachments/assets/7854db4c-b510-48c2-a8dc-d2043914c745)

**Comment by zcablii** [comment]
did you use the multi-scale split for fair1m test set?

**Comment by Huyifan626** [comment]
I just crop the test set into 1024x1024 size.How can I achieve the multi-scale split？

**Comment by Huyifan626** [comment]
After the multi-scale split,the result is good.The last question is how can I visualize a detection result image? Should I use the original-sized image or the cropped image?What is the command for visualizing detection results?

**Comment by zcablii** [comment]
you may find useful tutorials and instructions [here](https://github.com/zcablii/LSKNet/tree/main/docs/zh_cn)

**Comment by joannahuadu** [comment]
> ![image](https://github.com/user-attachments/assets/2a48d7f5-6310-4c29-98e2-772a0ebc65be) Have you ever meet this question?

Hi. How did you solve this problem? What formats did you change?

**Comment by joannahuadu** [comment]
> ![image](https://github.com/user-attachments/assets/2a48d7f5-6310-4c29-98e2-772a0ebc65be) Have you ever meet this question?

Is it only this one XML format (e.g., 7096.xml) that has a problem, or are there problems with all of them?
