### ISSUE TITLE
服务器训练自己的数据集

### ISSUE THREAD

**Issue by sun0629** [zcablii/LSKNet#89]
### Branch

master branch  https://mmrotate.readthedocs.io/en/latest/

### 📚 The doc issue

作者您好  我是刚入行的新手  请问在服务器上配置环境用自己的数据集跑lsknet模型的话是git clone https://github.com/zcablii/Large-Selective-Kernel-Network.git还是git clone https://github.com/open-mmlab/mmrotate.git，我看Installation和其中的[Install Guide](https://mmrotate.readthedocs.io/en/latest/install.html)安装方法有出入

**Comment by sun0629** [comment]
好的谢谢作者  我想问一下在服务器上配置完图片中的内容以后  自己的数据集（DOTA格式）应该放到哪个位置   有具体的关于训练自己数据集的步骤吗  
![Snipaste_2024-11-29_19-55-41](https://github.com/user-attachments/assets/a84f4caf-ca9d-422d-8abf-0cce9dc24692)

**Comment by zcablii** [comment]
放哪个位置不重要，只要在config文件里的数据集路径改成你的数据集路径即可。

**Comment by sun0629** [comment]
好的谢谢作者 请问config文件就是指的第一张图片中的这个文件吗  自己创建my_custom_config.py后是放到第二张图片中的configs/lsknet/还是放到configs/my_custom_config.py  完成配置文件后  然后再按照图中将①下载后放到指定位置是吗
![image](https://github.com/user-attachments/assets/cf852afa-6563-488c-bfc0-f8e74ba6e59a)
![Snipaste_2024-11-29_20-24-23](https://github.com/user-attachments/assets/86faed2e-8e7c-4e4c-bd36-f3511504f890)

**Comment by sun0629** [comment]
好的谢谢作者 请问config文件就是指的第一张图片中的这个文件吗 自己创建my_custom_config.py后是放到第二张图片中的configs/lsknet/还是放到configs/my_custom_config.py 完成配置文件后 然后再按照图中将①下载后放到指定位置是吗
![image](https://github.com/user-attachments/assets/54a03fd2-9752-45f4-88e2-2db9497e13e1)
![Uploading Snipaste_2024-11-29_20-24-23.png…]()

**Comment by sun0629** [comment]
好的谢谢作者 请问config文件就是指的第一张图片中的这个文件吗 自己创建my_custom_config.py后是放到第二张图片中的configs/lsknet/还是放到configs/my_custom_config.py 完成配置文件后 然后再按照图中将①下载后放到指定位置是吗
![image](https://github.com/user-attachments/assets/447b10be-4fcc-47ac-b6ec-4391aa7f7f0b)
![Snipaste_2024-11-29_20-24-23](https://github.com/user-attachments/assets/c8086559-5596-47ba-b4e9-41c701ddccfb)

**Comment by sun0629** [comment]
方便看一下简介中的邮箱吗

**Comment by sun0629** [comment]
方便去看一下简介中的邮箱吗

**Comment by zcablii** [comment]
建议看一下mmrotate框架的[教程](https://github.com/zcablii/LSKNet/tree/main/docs/zh_cn)。

**Comment by sun0629** [comment]
好的  谢谢作者解答
