### ISSUE TITLE
[Feature] dockerfile

### ISSUE THREAD

**Issue by neilvaltec** [zcablii/LSKNet#9]
### What's the feature?

Hi 
I tried to use the dockerfile to build an docker image testing on my mac using cpu only.
But it seems like it's not working.
Is the dockerfile updated?

thanks!

**Comment by zcablii** [comment]
Sorry, the dockerfile is not updated, please try to install the environment by command lines.

**Comment by neilvaltec** [comment]
Is it possible to update the dockerfile?
I try to run your model using cpu through
```
python demo/image_demo.py demo/demo.jpg rtmdet_tiny_8xb32-300e_coco.py --weights rtmdet_tiny_8xb32-300e_coco_20220902_112414-78e30dcc.pth --device cpu
````
from https://mmdetection.readthedocs.io/en/latest/get_started.html#verify-the-installation

But it did not work

**Comment by prashant-dn** [comment]
I suggest expanding on the environment where mmrotate works.

**Comment by wangaiping1024** [comment]
> Sorry, the dockerfile is not updated, please try to install the environment by command lines.
Hello author, can you tell me the mmvc-full version you are using? The latest version looks very incompatible.

**Comment by 7W7W7W** [comment]
Hello, may I ask why this is happening？
KeyError: "OrientedRCNN: 'LSKNet is not in the models registry'"
