### ISSUE TITLE
[添加新的模块] 在neck和roi_head中添加自己的特征处理模块

### ISSUE THREAD

**Issue by hias-lcj** [zcablii/LSKNet#91]
### Model/Dataset/Scheduler description

作者你好，我想在neck和head之间添加一个新的数据处理的模块，具体我应该怎么做呢？有没有相应的教程？

### Open source status

- [ ] The model implementation is available
- [ ] The model weights are available.

**Comment by zcablii** [comment]
You may find [docs here](https://github.com/zcablii/LSKNet/tree/main/docs)

**Comment by hias-lcj** [comment]
好的，谢谢！
