### ISSUE TITLE
[Docs] 关于数据预处理

### ISSUE THREAD

**Issue by stone-cloud** [zcablii/LSKNet#93]
### Branch

master branch  https://mmrotate.readthedocs.io/en/latest/

### 📚 The doc issue

很棒的工作！做了很多对比实验，有很多细节，非常感谢！我正在尝试本地复现[lsk做分割](https://github.com/zcablii/GeoSeg)的结果，根据教程对数据做了预处理，但结果无法复现，LoveDA只能达到0.43。我注意到原始路径是train_val，那么这个数据预处理是不是还有其他步骤？是把train和val合并到一起来做train训练吗？

**Comment by zcablii** [comment]
you can directly download the  preprocessed datasets here:
-[Vaihingen](https://pan.baidu.com/s/1SjOaZ55rUlghoggBcV1GCA?pwd=rssg) -[Potsdam](https://pan.baidu.com/s/1yihagJKRDs_9i2qrI2Lh4Q?pwd=rssg) -[LoveDA](https://pan.baidu.com/s/1OkeOrVQ1kvoxF7zYCdKz1Q?pwd=rssg) -[uavid](https://pan.baidu.com/s/1FEvaU41Ay6D5Js7QwD4CGQ?pwd=rssg)

**Comment by stone-cloud** [comment]
> you can directly download the preprocessed datasets here: -[Vaihingen](https://pan.baidu.com/s/1SjOaZ55rUlghoggBcV1GCA?pwd=rssg) -[Potsdam](https://pan.baidu.com/s/1yihagJKRDs_9i2qrI2Lh4Q?pwd=rssg) -[LoveDA](https://pan.baidu.com/s/1OkeOrVQ1kvoxF7zYCdKz1Q?pwd=rssg) -[uavid](https://pan.baidu.com/s/1FEvaU41Ay6D5Js7QwD4CGQ?pwd=rssg)

谢谢，我用这个数据和原始代码参数复现，LSK-s达到了0.525，预训练权重使用的是[本仓库的](https://download.openmmlab.com/mmrotate/v1.0/lsknet/backbones/lsk_s_backbone-e9d2e551.pth)，我不知道为什么会有0.015的差距，能不能给出你训练的参数和配置环境呢？或者有没有什么需要注意的地方？

**Comment by zcablii** [comment]
请使用[这里](https://github.com/zcablii/GeoSeg/tree/main/config/loveda)的config，用8卡跑

**Comment by stone-cloud** [comment]
好的，请问预训练权重是怎么得到的？有相关代码或配置文件吗？

**Comment by zcablii** [comment]
> 好的，请问预训练权重是怎么得到的？有相关代码或配置文件吗？

请[参考](https://github.com/zcablii/LSKNet/issues/7)
