### ISSUE TITLE
模型参数问题

### ISSUE THREAD

**Issue by sun0629** [zcablii/LSKNet#94]
### Model/Dataset/Scheduler description

您好作者，请问lsknet网络模型是属于大模型还是小模型   数量级是多少

### Open source status

- [ ] The model implementation is available
- [ ] The model weights are available.

**Comment by zcablii** [comment]
正如论文题目指出，“LSKNet: A Foundation **Lightweight** Backbone for Remote Sensing”，LSKNet是轻量化的小模型，文中给出的参数量如下。尽管其参数量较少，但文中展示的性能数据表明，LSKNet在各项下游任务中的表现均优于那些参数量更大的对比模型。
![image](https://github.com/user-attachments/assets/24a5696a-05db-4182-960e-d3dbbc3afc89)

**Comment by sun0629** [comment]
好的 谢谢您的回复
