### ISSUE TITLE
数据增广方式

### ISSUE THREAD

**Issue by sun0629** [zcablii/LSKNet#95]
### Model/Dataset/Scheduler description

您好作者   麻烦问一下在使用lsknet模型训练自己的数据集的时候   默认的数据增广方式有哪一些  （我想在想训练自己的数据集  但是数据量不够  所以需要对自己的数据集进行数据增广）

### Open source status

- [ ] The model implementation is available
- [ ] The model weights are available.

**Comment by zcablii** [comment]
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='RResize', img_scale=(1024, 1024)),
    dict(type='RRandomFlip', flip_ratio=0.5),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels'])
]
